FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    git \
    curl \
    build-essential \
    ca-certificates \
    gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -g @qwen-code/qwen-code@latest

# Create virtual environment
RUN python3 -m venv /opt/venv

# USER begin
ARG USER_ID=1000
ARG GROUP_ID=1000

RUN groupadd -g ${GROUP_ID} ubuntu && \
    useradd -l -u ${USER_ID} -g ubuntu -m ubuntu

RUN chown -R ubuntu:ubuntu /opt/venv
USER ubuntu
# USER end

# Set environment variables so the system sees venv first
ENV PATH="/opt/venv/bin:$PATH"

COPY ./requirements.txt /tmp/requirements.txt

RUN pip3 install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /workspace
